#!/usr/bin/env node

// Generate separate compression-only and decompression-only modules
//
// This script reads lzma_main.ts and generates stripped versions:
// - compress-only.ts: removes decompression code (markers: ds to de)
// - decompress-only.ts: removes compression code (markers: cs to ce)
//
// The markers in lzma_main.ts are JSDoc-style comments:
// - cs/ce - compression start/end
// - ds/de - decompression start/end
// - xs/xe - master file only (removed in both)

import fs from 'fs'
import path from 'path'
import { build as bundleWithEsbuild } from 'esbuild'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const srcDir = path.join(__dirname, '..', 'src')
const generatedDir = path.join(srcDir, 'generated')
const sourceFile = path.join(srcDir, 'lzma_main.ts')

// Ensure generated directory exists
if (!fs.existsSync(generatedDir)) {
  fs.mkdirSync(generatedDir, { recursive: true })
}

// Read source file
const source = fs.readFileSync(sourceFile, 'utf-8')

/**
 * Remove content between markers (inclusive of markers)
 */
function stripMarkers(content, startMarker, endMarker) {
  // Create regex to match from start marker to end marker (including markers)
  // Using [\s\S] to match any character including newlines
  const regex = new RegExp(
    `\\/\\*\\*\\s*${startMarker}\\s*\\*\\/[\\s\\S]*?\\/\\*\\*\\s*${endMarker}\\s*\\*\\/`,
    'g',
  )
  return content.replace(regex, '')
}

// Generate compress-only module
console.log('Generating compress-only module...')
let compressOnly = source

// Strip decompression blocks and master-file-only blocks
compressOnly = stripMarkers(compressOnly, 'ds', 'de')
compressOnly = stripMarkers(compressOnly, 'xs', 'xe')

// Add header comment with @ts-nocheck to suppress unused variable warnings
const compressHeader = `// @ts-nocheck
/**
 * LZMA Compression Only Module
 *
 * This is an auto-generated file containing only compression functionality.
 * For tree-shaking: import from 'lzma-web/compress'
 *
 * DO NOT EDIT - Generated by scripts/generate-modules.js
 */

`

compressOnly = compressHeader + compressOnly

// Clean up multiple empty lines
compressOnly = compressOnly.replace(/\n{3,}/g, '\n\n')

fs.writeFileSync(path.join(generatedDir, 'compress-only.ts'), compressOnly)
console.log(`  Created: src/generated/compress-only.ts`)

// Generate decompress-only module
console.log('Generating decompress-only module...')
let decompressOnly = source

// Strip compression blocks and master-file-only blocks
decompressOnly = stripMarkers(decompressOnly, 'cs', 'ce')
decompressOnly = stripMarkers(decompressOnly, 'xs', 'xe')

// Add header comment with @ts-nocheck to suppress unused variable warnings
const decompressHeader = `// @ts-nocheck
/**
 * LZMA Decompression Only Module
 *
 * This is an auto-generated file containing only decompression functionality.
 * For tree-shaking: import from 'lzma-web/decompress'
 *
 * DO NOT EDIT - Generated by scripts/generate-modules.js
 */

`

decompressOnly = decompressHeader + decompressOnly

// Clean up multiple empty lines
decompressOnly = decompressOnly.replace(/\n{3,}/g, '\n\n')

fs.writeFileSync(path.join(generatedDir, 'decompress-only.ts'), decompressOnly)
console.log(`  Created: src/generated/decompress-only.ts`)

console.log('Generating inline worker module...')
const workerBundle = await bundleWithEsbuild({
  entryPoints: [path.join(srcDir, 'worker-thread.ts')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2020',
  write: false,
  minify: true,
})

const workerSource = workerBundle.outputFiles[0]?.text

if (!workerSource) {
  throw new Error('Failed to generate inline worker bundle')
}

const workerInlineSource = `/**
 * Inlined worker bundle used by createWorkerLZMA().
 *
 * DO NOT EDIT - Generated by scripts/generate-modules.js
 */

export const workerThreadSource = ${JSON.stringify(workerSource)}
`

fs.writeFileSync(path.join(generatedDir, 'worker-inline.ts'), workerInlineSource)
console.log(`  Created: src/generated/worker-inline.ts`)

console.log('Done!')
